# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.generic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name=b'First name of the user')),
                ('last_name', models.CharField(max_length=100, verbose_name=b'Lat name of the user')),
                ('iban', localflavor.generic.models.IBANField(default=None, max_length=34)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'uploads/', verbose_name=b'Image of the user')),
            ],
        ),
    ]
